### ISSUE TITLE
Eliminate PDF documentation from repo

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#131]
Most of the gen 1 PODs provided their documentation in PDF format, and some of the PRs for gen 2 PODs are doing the same. This poses a problem, since we now have two redundant copies of the POD documentation (the PDFs, and the .rst files used for the documentation website), which have the potential to go out of sync. 

Checking in binary files to a git repo is undesirable (although the PDFs are small and we don't anticipate lots of changes.), and PDF files are (slightly) less accessible than the HTML output: since the package output is HTML, it's more natural to link to HTML documentation rather than start up the user's browser's PDF plugin.

I propose that 
- All PDF files should be deleted from the repo, with the .rst files serving as the unique source of documentation for each POD (I think this is what's currently proposed in the developer instructions, but these should be updated if not);
- Links to these PDF files in the output HTML should be replaced with links to the corresponding page on the [documentation website](https://mdtf-diagnostics.readthedocs.io/en/latest/index.html), which will eliminate duplicate copies of these files in the output when the package is run repeatedly;
- We provide the option to use sphinx to compile the POD documentation from source and link to that in the output, instead of the external web site, in order to accommodate the use case where incoming HTTP/HTTPS connections are blocked on the system where the package is running (or the system where the output data is stored).

**Comment by wrongkindofdoctor** [comment]
@tsjackson-noaa Agreed. Eliminating PDFs will streamline the documentation and clear some of the repo clutter.

**Comment by jkrasting** [comment]
Yes, the PDFs are going to cause us issues in the future.  I agree with this.

**Comment by tsjackson-noaa** [comment]
Just to be safe, I archived all the PDF documentation in the collaboration shared google drive folder (`MDTF2_Task-Force_share/old_POD_documentation_PDFs`). In converting the PDFs to .rst files, I preserved all the text and was able to recreate most of the formatting, but it still may be necessary to refer back to these files to fix typos in the .rst files, etc.
