### ISSUE TITLE
Potential issue with conda init

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#143]
Hi @wrongkindofdoctor -- requesting your feedback on the following:

You mentioned needing to add the conda installer's script to your .bashrc to get the package to run. If the package wouldn't run before you did this, that's a pretty serious issue, and I'd like to get more info on the steps to reproduce it.

**Details:**
Conda is implemented as a shell alias, which poses lots of problems if you want to invoke it from a script (non-interactive shell). I'm unaware of a best practice for doing so, and would welcome advice -- this issue has popped up a number of times. 

The current solution (in both beta-2 and beta-3) is to have the user set the path to the conda installation as part of the package configuration (the `--conda_root` flag -- this is in the [docs](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/start_install.html#configure-framework-paths)). In every situation where the package needs to use conda, it first sources the [src/conda/conda_init.sh](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/src/conda/conda_init.sh) script, which takes this path as an argument.

Most of the content of conda_init.sh is finding the conda executable (one of the code paths is when this location is passed as an argument). When this is found, it runs the same [shell script](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/6c71a7833f403fe43c81c4d8e709b01d07937583/src/conda/conda_init.sh#L127-L141) as what's  inserted into .bashrc by the conda installer. (We only source the user's .bashrc [more correctly, start a subshell in [interactive mode](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/6c71a7833f403fe43c81c4d8e709b01d07937583/src/conda/conda_init.sh#L74)] directly as a last resort, since doing so might invoke all kinds of other stuff that would wreck the environment we're trying to set up, or at least make it non-reproducible.)

The upshot is that I *thought* this code made the package completely independent of what's in the user's .bashrc/.cshrc/..., as long as the user set `--conda_root`; e.g., through a configuration file). If you're setting `conda_root` (e.g., to the mdteam site installation at `/home/mdteam/anaconda`) but still need to put those lines in your .bashrc to get the package to run, that's a problem. 

I can try making a new, dummy user on my home machine and doing an install from scratch to see if that will reproduce the issue -- other than that, any details you can provide would be helpful.

**Comment by wrongkindofdoctor** [comment]
@tsjackson-noaa This issue appears to have resolved following the update of the installation on PPAN. After switching shells, I can run 
`/home/mdteam/DET/analysis/mdtf/MDTF-diagnostics/mdtf -f /home/jml/mdtf/MDTF-diagnostics/sites/NOAA_GFDL/default_gfdl.jsonc --site NOAA_GFDL` without having to source my ~/.bashrc file.
