### ISSUE TITLE
Error reading in static variables

### ISSUE THREAD

**Issue by jeyavinoth** [NOAA-GFDL/MDTF-diagnostics#164]
@jkrasting, @tsjackson-noaa, @wrongkindofdoctor @jfbooth: 

When I try to read in statics files that I require for the POD, I keep getting the following error: 
It is looking for a "time" dimension, which does not exist. 

WARNING: Execution of POD etc_composites couldn't be completed:
***** Caught exception #1:
Traceback (most recent call last):
  File "/localdrive/drive10/jj/mdtf/MDTF-diagnostics/src/data_manager.py", line 387, in setup_pod
    self.setup_var(pod, v)
  File "/localdrive/drive10/jj/mdtf/MDTF-diagnostics/src/data_manager.py", line 418, in setup_var
    range=self.attrs.date_range
  File "/localdrive/drive10/jj/mdtf/MDTF-diagnostics/src/data_model.py", line 446, in change_coord
    raise KeyError(f"{self.name} has no {ax_name} axis")
KeyError: 'sftlf has no T axis'

The varlist section of the settings.jsonc file when I try to read in the 'land_area_fraction' is as follows: 
  "varlist" : {
    "sftlf": {
      "standard_name" : "land_area_fraction",
      "dimensions": ["lat", "lon"],
      "use_exact_name": true
    }

How should I proceed with this error? 

Thanks, 
JJ

**Comment by jeyavinoth** [comment]
@jkrasting, @tsjackson-noaa, @wrongkindofdoctor @jfbooth:

any updates on how to proceed with this issue? 

Thanks, 
JJ

**Comment by jkrasting** [comment]
Nothing new, @jeyavinoth but I also see this with @chiaweh2's POD:

```
### Framework: initialize CESM2_omip1_r1i1p1f1_gn
WARNING: No non-console-based loggers configured.
WARNING: Deactivating <#2.tropical_pacific_sea_level:zos> due to translation failure ("Standard name 'sea_surface_height_above_geoid' not defined in convention 'NCAR'.").
WARNING: Deactivating <#3.tropical_pacific_sea_level:tauuo> due to translation failure ("Standard name 'downward_x_stress_at_sea_water_surface' not defined in convention 'NCAR'.").
WARNING: Deactivating <#4.tropical_pacific_sea_level:tauvo> due to translation failure ("Standard name 'downward_y_stress_at_sea_water_surface' not defined in convention 'NCAR'.").
ERROR: 'areacello has no T axis'
Traceback (most recent call last):
  File "/home/jpk/mdtf/MDTF-diagnostics/src/data_manager.py", line 387, in setup_pod
    self.setup_var(pod, v)
  File "/home/jpk/mdtf/MDTF-diagnostics/src/data_manager.py", line 418, in setup_var
    range=self.attrs.date_range
  File "/home/jpk/mdtf/MDTF-diagnostics/src/data_model.py", line 446, in change_coord
    raise KeyError(f"{self.name} has no {ax_name} axis")
KeyError: 'areacello has no T axis'
```

**Comment by wrongkindofdoctor** [comment]
From what I can tell, the l change_coord routine in [setup_var](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/f82d37a0b46e0b4e73bdfb59940c95e16b57fb23/src/data_manager.py#L408) is a run-time routine that assumes that all variables will have a Time (T) axis. I will need @tsjackson-noaa to confirm. If this is the case, we should add some logic to the data manager to check variables for time, and skip the conversion if there is no time axis rather than throwing a key error.

**Comment by jeyavinoth** [comment]
@jkrasting @tsjackson-noaa @jfbooth

I realize that a fix for static variables was implemented, but I cannot seem to get it working. 

Can you provide an example of how to load a static variable via the settings.jsonc file? (especially "sftlf" (land_area_fraction) and "orog" (surface_altitude))?

1. How should I configure the static variable in the settings.jsonc file? 
Should I provide the "frequency" attribute in the varlist section? What changes do I need to make in the following? 
    "sftlf": {
      "standard_name" : "land_area_fraction",
      "units": "1",
      "dimensions": ["lat", "lon"], 
      "use_exact_name": true
    }, 
2. Where should I save the inputdata for the static files? In the appropriate frequency folder (i.e. for 6hr --> ../inpudata/model/<CASENAME>/6hr/<CASENAME>.orog.6hr.nc)?

3. Can you provide a sample data for the static variable such as "orog" and "sftlf", to understand how the data is stored in netcdf files? 


One of the errors I receive is: 
DEBUG: <#sentinel.NotSet.etc_composites:sftlf (=(not translated)); active:NOTSET, failed (exc=argument of type 'NoneType' is not iterable), required>

Thanks, 
JJ

**Comment by jkrasting** [comment]
Here is what I have @jeyavinoth, but I am also running into similar trouble.  I'll touch base with @tsjackson-noaa and @wrongkindofdoctor.

```
      "areacello": {
        "standard_name": "cell_area",
        "units": "m2",
        "dimensions" : ["lat", "lon"]
        }
```

My log is attached.
[MDTF_log.txt](https://github.com/NOAA-GFDL/MDTF-diagnostics/files/6442995/MDTF_log.txt)

**Comment by jkrasting** [comment]
The fix I suggested yesterday was indeed messing with the time slice extraction.  I isolated the problem a bit further to the  [`change_coord()`](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/develop/src/data_model.py#L439) function.  The data manager is attempting to reassign a non-existent time dimension.  This quick fix simply exists the function in the case where an old/existing coordinate is a `None` type.

This fix (https://github.com/NOAA-GFDL/MDTF-diagnostics/pull/209/commits/b888bd8f6de11fe8c5dabe6286267e21787ae7d2) *seems* to address the issue without introducing any new issues.

**Comment by jeyavinoth** [comment]
@jkrasting @wrongkindofdoctor @jfbooth
Yes this fixed it. Thanks!
