### ISSUE TITLE
documentation sections 9.5 & 9.6 contain the same information 

### ISSUE THREAD

**Issue by bitterbark** [NOAA-GFDL/MDTF-diagnostics#173]
Section 9.6. (Pushing to your remote feature branch on your fork)
repeats steps 3-5 of 9.5. (Working on a brand new feature)
although 9.6 has better explanations of what is going on

https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_git_intro.html#ref-new-feature

**Comment by tsjackson-noaa** [comment]
Any preference for which section we keep, @wrongkindofdoctor, or should I take a shot at combining them?

**Comment by wrongkindofdoctor** [comment]
@tsjackson-noaa I think subbing a reference to section 9.6 for steps 3--5 in step 9.5 would be one of the simplest modifications.

**Comment by tsjackson-noaa** [comment]
Closing this issue because PR #231 has been merged.
