### ISSUE TITLE
Remote data via intake-esm catalogs

### ISSUE THREAD

**Issue by mgrover1** [NOAA-GFDL/MDTF-diagnostics#193]
Are there current plans to implement the ability to use intake-esm catalogs (ex. `https://storage.googleapis.com/cmip6/pangeo-cmip6.json`) within this framework? Could this be specified within the .jsonrc file as a parameter (essentially replacing the `MODEL_DATA_ROOT` when you are interested in remote data)?

**Comment by jkrasting** [comment]
Hi @mgrover1.  It is something we have discussed, but we don't have a definite plan or timeline.  Tagging @aradhakrishnanGFDL in this thread.
