### ISSUE TITLE
Specify whether CLI arguments are required or optional

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#275]
The [CLI documentation](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/doc/sphinx/ref_cli.rst) does not include information on whether arguments are required or optional, which has caused some issues with running the framework.

**Comment by tsjackson-noaa** [comment]
Hi @wrongkindofdoctor, I saw that you had opened this issue but didn't see that you had self-assigned it until after I finished PR #276. Please verify that it addresses this issue.

**Comment by wrongkindofdoctor** [comment]
@tsjackson-noaa Thanks, Tom! FWIW, any issues that I open will be assigned to @wrongkindofdoctor (unless we have agreed that someone else should take on a task beforehand at a meeting or something), and reaching out for assistance if needed.
