### ISSUE TITLE
Requesting source code DOI for MDTF phase-2

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [NOAA-GFDL/MDTF-diagnostics#278]
**What problem will this feature solve?**

It will be nice to wrap up phase-2 with a code DOI as we begin the new phase, to acknowledge (and cite work of ) the previous team.

**Describe the solution you'd like**

A DOI tied to a specific version/branch/tag as the developer and team sees fit. The solution can be implemented via Zenodo fairly quickly, once the team agrees. 

**Describe alternatives you've considered**

None

**Additional context**

**Comment by bitterbark** [comment]
If we still want to obtain the DOI from NCAR, these are the outstanding requests from the people in charge of DOI issuance:

REQUIRED:
One DOI for diagnostic package, or DOIs for each diagnostic listed on the MDTF page?
Web page target for the DOI to point to.

Creators - [people or group responsible for creating the resource[
Title  - [
Publisher - [Recommended] UCAR/NCAR - Climate and Global Dynamics  (Dani: I imagine we will want something different from this!)
PublicationYear - [usually used to indicate either: 1) the year that the resource was first publicly available, and/or 2) the year a specific "release" was made.]

Point of Contact - [could be an individual person's email, or an email alias if applicable]
Description/Abstract - [brief description of the software, e.g. one paragraph or less]
Version - [Version of the software, if this is applicable and important for the users]
Format - [what code language, e.g. python, fortran, C, etc]
license - [is there a standard set of usage terms for the software? this could be a link to another page if the license is given on your website somewhere]
