### ISSUE TITLE
Update tropical sea level POD with obs. and unit tests

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#280]
The tropical sea level pod (#271) needs obs data.  @bitterbark -- here is a tarball with the files.  Could you add this in with the rest of the obs data?  `ftp://ftp.gfdl.noaa.gov/pub/John.Krasting/mdtf/obs/tropical_pacific_sea_level.20211006.tar.gz` 

@wrongkindofdoctor - we also need to work in the coarse-resolution ocean test data for the CI.

**Comment by bitterbark** [comment]
Did you make it with the necessary flags or do I need to remake it? Are we
posting gzipped because it is larger than 1GB? Should we do that with
everyone's?

**Comment by jkrasting** [comment]
I did not use the `--hard-deference` flag, but the tar file did not have
any symlinks in it so it should be good to go.  Would you mind just
double-checking that you can open it?

Good question about the gzip option.  I didn't even think about that - I
typically compress everything that contains ocean data.  I am fine with
both `.tar` and `.tar.gz` files.  What do you think?

**Comment by jkrasting** [comment]
Good catch. I think we can delete that file. It should also help with the
file size.

The untar and unzip can be done all in one step with “tar -xzvf”.
--
