### ISSUE TITLE
Add multi-run functionality to framework

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#309]
**What problem will this feature solve?**
Support PODs that analyze output from multiple cases/ensemble members

**Describe the solution you'd like**
* Framework will ingest ensembles as different cases
* case input structure be reorganized as a case list with ensemble names, firstyr,lastyr, and other descriptors in environment jsonc config file (default_tests.jsonc)
* Plan for eventual transition from jsonc to yaml for case and environment input
* case list will be placed in a dictionary for ingestion by framework and PODs
* Collaborators will help extend current example POD to process a multiple (2-3) cases  of temperature data and generate a simple plot (e.g., timeseries, zonal mean)

**Additional context**
Related discussion #148

**Comment by aradhakrishnanGFDL** [comment]
Hi @wrongkindofdoctor, We originally discussed jsonc implementation first and then transition to yaml, though I see the cost benefits for both, from POD dev standpoint as well. Based on the following on the issue description, please confirm if you're considering yaml for this prototype.

> case input structure will be placed in a yaml instead of jsonc file and reorganized as a case list with ensemble names, firstyr,lastyr, and other descriptors

This also means we need an update to the design specs to add a sample YAML settings file for a POD that can be passed to @jkrasting. @jkrasting the [design doc ](https://docs.google.com/document/d/1ynWIeU-SRRyySyR679mD2WZ6SMjSetth2m88GvT6pWI/edit)has the dictionary info, please ping on this issue for any additional info. 

> case input structure will be placed in a yaml instead of jsonc file and reorganized as a case list with ensemble names, firstyr,lastyr, and other descriptors

**Comment by wrongkindofdoctor** [comment]
@aradhakrishnanGFDL I have edited the the issue text to reflect that we will use jsonc first, then move to yaml.

**Comment by bitterbark** [comment]
As users start using the multi-run capability, we should update the documentation based off of their experience. For instance, based on Ryan Kramer's experience, we should make it obvious right up front that the user doesn't modify the yaml files that are found in the example pod directory but instead these are created by the framework. A step by step instruction for how to run the framework initially to create these files before a developer starts working on a new POD would be useful. I'm happy to write this, with Ryan & @wrongkindofdoctor's help.
