### ISSUE TITLE
More permissible handling of time encoding/units

### ISSUE THREAD

**Issue by zdlawrence** [NOAA-GFDL/MDTF-diagnostics#328]
**What problem will this feature solve?**

I have a collection of CMIP6 monthly mean data; some of these files are saved with time encoding units of "days since XYZ", while others are saved with "hours since XYZ". In developing my own POD, I have found that the framework will fail on the latter set of data (hours), but has no issue with the former (days). I think this is because I do not specify the time units in my settings.jsonc file, which defaults to "days" (as per the docs [here](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_settings.html)). I get error messages like the following:

`DataPreprocessEvent("Received event while parsing file metadata for <#dl6X:stc_eddy_heat_fluxes.zg>: MetadataEvent("Unexpected units for variable 'time': 'hours since 1850-01-16T12:00:00' (expected 'days').").")`

However, this behavior is a bit confusing when considering the docs [here](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/ref_data.html)  which state: 

> The time coordinate of the data must follow the CF conventions. 

As far as I know, the "hours since XYZ" encoding is compliant with CF conventions. 

**Describe the solution you'd like**

It would be ideal if the time handling in MDTF would be more permissible to not require a default unit/encoding unless specifically set by POD developers. I assume MDTF uses xarray under the hood to read/handle model data, and it has no issues decoding the time in these cases, so why should PODs fail to run if they are agnostic to the way the times are encoded?

Admittedly, I have not thought of the consequences of such a change. I also cannot rule out the possibility that I'm misunderstanding something with the way the framework runs or the CF conventions -- in which case, I apologize for the unnecessary issue!

**Comment by wrongkindofdoctor** [comment]
@zdlawrence Thank you for this information. I agree that there is no reason that the framework should not be able to handle hours or any other set of CF-compliant time conventions. If you can share your working branch (and push whatever you have on your local copy of your MDTF-diagnostics fork), and your test data (email or link to ftp server for downloading), I can do a deeper dive and try to resolve the problem.

**Comment by zdlawrence** [comment]
@wrongkindofdoctor - Sure thing. Please see my branch at https://github.com/zdlawrence/MDTF-diagnostics/tree/feature/stc_eddy_heat_fluxes. I've provided test data (including observational inputdata) in a tarball via ftp, which you can access at ftp://ftp.cdc.noaa.gov/pub/Public/zlawrence

I've provided two sets of data that are equivalent -- one uses "days since XYZ" encoding, which allows the POD to complete successfully, while the other uses "hours since XYZ" encoding (this is the CNRM-CM6-1_CMIP_amip_r1i1p1f2_hour-enc data), which causes the POD to fail. 

I've also provided the MDTF output from the successful run so you can peruse those for config settings/logs and compare results.
