### ISSUE TITLE
Inability to robustly prescribe component preference

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#335]
**Bug Severity**  
* [ ] **1 = Minor problem** that does not affect total framework functionality (e.g., computation error in a POD, problem with logging output, or an issue on a single system  
* [x] **2 = Major problem** that affects overall functionality, but that does not occur for all users (e.g., problems installing the framework with a specific Conda version, a framework option that causes one or more PODs to fail, or missing/incompatible Python modules).  
* [ ] **3 = Catastrophic problem** that occurs frequently for multiple users and/or on multiple systems (e.g.,framework consistently fails to install on multiple systems, or one or more PODs continuously fails after running successfully) 

**Describe the bug**
The [data selection heuristics](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx_sites/NOAA_GFDL.html#results-of-frepp-processed-runs) for FREPP-processed data are yielding undesirable results for ocean fields.  Here is a specific case example that considers the ocean variable `tos` or `sea_surface_temperature`.  The field exists traditionally in three frepp components:

1. atmos_cmip
2. ocean_monthly
3. ocean_monthly_1x1deg

The current heuristics would select the version from _atmos_cmip_ (since it contains the sub-string "_cmip_").  This selection would be undesirable from an ocean modeler's perspective.  Even if the _atmos_cmip_ component was ignored, the second criteria of selecting the component with the shortest name (_ocean_monthly_ in this case) would not always be appropriate for high-resolution models.

**Steps To Reproduce**
- Add `tos` to the `fieldlist_CMIP.jsonc` file
- Create a dummy POD that tries to read `tos`

**Environment**
- GFDL central install

**Comment by wrongkindofdoctor** [comment]
@jkrasting Much appreciated. I will add this to the top of this week's todo list.

**Comment by jkrasting** [comment]
No action needed on your part @wrongkindofdoctor - I am close to having a fix.  Once I have something, I'd like to run it by the team to make sure we are on the same page.
