### ISSUE TITLE
disable-preprocessor flag causing error

### ISSUE THREAD

**Issue by bitterbark** [NOAA-GFDL/MDTF-diagnostics#352]
**Bug Severity**  
* [ 1] **1 = Minor problem** that does not affect total framework functionality (e.g., computation error in a POD, problem with logging output, or an issue on a single system  

**Describe the bug**
I'm trying to run with the --disable-preprocessor flag that I saw in Jess' tutorial, and I think it is failing to recognize the argument, or I'm giving it wrong, or maybe running into another bug. Thanks for any ideas.

**Steps To Reproduce**

> ./mdtf -f src/input_dani.jsonc --disable-preprocessor
 

**Environment**
Describe the system environment:
- OS: [e.g. RHEL 7.2]
- Conda version: [the `conda info` command will provide the installation information] 
- branch name and link: [e.g., develop, https://github.com/NOAA-GFDL/MDTF-diagnostics/tree/develop]

the latest code from GFDL main branch 
685b696 - Jess, 5 days ago : Merge develop updates into main branch (#348)

**Log information and/or terminal output**
Copy information from any output logs and/or the terminal that might help with debugging.
> CRITICAL: Framework caught exception TypeError("_log() got an unexpected keyword argument 'tags'")
> Traceback (most recent call last):
>   File "/glade/u/home/bundy/mdtf/MDTF_3_main/MDTF-diagnostics/src/core.py", line 794, in __init__
>     self.configure(cli_obj, pod_info_tuple, log_config)
>   File "/glade/u/home/bundy/mdtf/MDTF_3_main/MDTF-diagnostics/src/core.py", line 815, in configure
>     self.parse_mdtf_args(cli_obj, pod_info_tuple)
>   File "/glade/u/home/bundy/mdtf/MDTF_3_main/MDTF-diagnostics/src/core.py", line 858, in parse_mdtf_args
>     self.parse_flags(cli_obj)
>   File "/glade/u/home/bundy/mdtf/MDTF_3_main/MDTF-diagnostics/src/core.py", line 870, in parse_flags
>     "preprocessor."), tags=util.ObjectLogTag.BANNER)
>   File "/glade/work/bundy/miniconda2/envs/_MDTF_base/lib/python3.7/logging/__init__.py", line 1390, in warning
>     self._log(WARNING, msg, args, **kwargs)
> TypeError: _log() got an unexpected keyword argument 'tags'

Note that without the --disable-preprocessor flag, it reads in the input json file just fine and then fails on the dataset (which is why I'm trying to use the flag!)

**Comment by wrongkindofdoctor** [comment]
@bitterbark It looks like the `disable-preprocessor` flag exposed a bug in the python logger. I have merged the fix into the develop and main branches, so you can go ahead and update your fork.

**Comment by bitterbark** [comment]
Whoops, sorry I hadn't successfully 'git pulled'. Got the new code now and the error is fixed regarding the 'tag' item. 

However, disabling the preprocessor did not help with the failure to read the data. More on that to come, I'm sure.
