### ISSUE TITLE
Can't access the develop branch mentioned in the docs to create a new POD branch

### ISSUE THREAD

**Issue by jcstarr** [NOAA-GFDL/MDTF-diagnostics#403]
I am a graduate student at FSU working under my advisor Allison Wing in developing a POD for tropical disturbance MSE variance budgets. When working on building a POD and creating a new POD branch from the develop branch, I am not seeing the develop branch that is mentioned in the docs. I also took a look at the developer walkthrough PDF and when I click on the develop branch hyperlink on page 7, I am taken to a "404 Web Page Not Found" on github. I am not sure if this is naive or not, but I am not sure why I can't access this. Thank you for future guidance. 
<img width="750" alt="Screenshot 2022-09-21 at 4 38 42 PM" src="https://user-images.githubusercontent.com/109545054/191605827-68a0dbf5-f618-4506-bd08-966a8d3d76d1.png">

**Comment by wrongkindofdoctor** [comment]
@jcstarr All PR's are submitted to the main branch now. I apparently missed this line in the docs when I was updating them a while back, and will fix this.
