### ISSUE TITLE
Trailing whitespace in QBOi.EXP1.AMIP.001/1hr metadata

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#41]
Requesting @bitterbark 's assistance on this.

Metadata for all four of the 1hr-frequency variables in the supplied QBOi.EXP1.AMIP.001 sample data has a large amount of trailing whitespace. This produces errors when read in NCL, xarray, etc. -- the specific error that's raised is that they can't recognize the 'calendar' attribute `'noleap    '` as the `noleap` calendar. This occurs in the current version of the data (ftp://ftp.cgd.ucar.edu/archive/mdtf/model.QBOi.EXP1.AMIP.001.20200730.tar).

This is a followup to an issue raised in an internal email on Apr 9 2020 -- I mistakenly said that above problem only affected the daily wind velocities for this model, and @bitterbark quickly fixed and reposted the data. I'm at fault for not testing and characterizing the scope of the issue back then.

**Comment by bitterbark** [comment]
Will fix on my next work day (Tuesday).

**Comment by jkrasting** [comment]
Fixing the source data is good idea.

Historically, GFDL has had case issues with the `noleap` calendar attribute:  both `NOLEAP` and `noleap` appear in our internal data.  In this case, we might need a lightweight routine to standardize attributes.  Removing trailing whitespace could be part of that.

**Comment by tsjackson-noaa** [comment]
Agreed -- this is a major piece of functionality we need to implement in a more scalable way if we want to handle translation from the native output of more models.

In a narrow sense, I've got a fix that just opens the file with minimum functionality, does whatever munging we want to do on the headers, and only afterwards calls [xarray.decode_cf()](http://xarray.pydata.org/en/stable/generated/xarray.decode_cf.html) or other parsing based on the values of these headers. The broader issue is that there doesn't seem to be standard code that we can easily call out to in order to munge the headers -- [CMOR](https://github.com/PCMDI/cmor) seems to do everything in C, and fremetar is in perl and GFDL-specific.

**Comment by bitterbark** [comment]
Reposted  ftp://ftp.cgd.ucar.edu/archive/mdtf/model.QBOi.EXP1.AMIP.001.tar (symbolic link to model.QBOi.EXP1.AMIP.001.20200818.tar) with whitespace removed from the 4 1hr/ files.  My mistake for only looking at the daily files last time. Confirmed no other faulty files in QBOi distribution.

**Comment by tsjackson-noaa** [comment]
Great! Thanks @bitterbark !
