### ISSUE TITLE
'[50, 75, 62, 5]' should be '[50, 75, 62.5]'

### ISSUE THREAD

**Issue by huangynj** [NOAA-GFDL/MDTF-diagnostics#434]
https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/5f8b01a84e7f34d600710903fc307682f5c62d3d/diagnostics/TC_Rain/TC_rain.py#L234

**Comment by wrongkindofdoctor** [comment]
@huangynj Good catch! This has been fixed and merged into the main branch.
