### ISSUE TITLE
Add capability to check for pre-exisiting processed files before running preprocessor

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#437]
**What problem will this feature solve?**
This will mitigate the overhead of reading and writing files during the preprocessing step every time the framework is run
**Describe the solution you'd like**
Per #436 

> ...[A] situation where you run the framework with a specific POD/dataset combination with the `--keep-temp` flag (and `--disable-preprocessor` flag if you don't want any of the variable name/metadata modifications) enabled to retain the local copies of the files. Next, you want to re-run the same configuration using the saved local files. With a new flag (e.g., `--no-file-rw`), the framework would have to search for any preexisting working directories with the desired CASENAME for saved files. If it finds the files, it sets the file path and variable name environment variables to point to the old wk_dir, and skips the preprocessing. If it doesn't find those files, it would run the standard configuration with the preprocessor.

**Additional context**
This feature implementation may occur in conjunction with the separation and redesign of the preprocessor. It will also provide an opportunity to incorporate intake_esm catalogs.

**Comment by wrongkindofdoctor** [comment]
@Okay.1a, 1b, and Na fit with the current paradigm. Nb is where I'm lost. Unless`--overwrite` is specified, a new WK_DIR will be created, where WK_DIR is [root]/wkdir/[CASENAME]_[version number]. The _[version number] is appended if [root]/wkdir/[CASENAME] already exists, and increments by 1 each time the framework is run if [root]/wkdir is not cleaned by the user. The only way for Nb to work is if the framework queries previously created [root]/wkdir directories with CASENAME (or perhaps just for the directory with CASENAME_[current version number -1 ]) that contain saved processed data files.

**Comment by bitterbark** [comment]
I'm available to chat if you want, meet.google.com/vyk-szuh-etu

**Comment by bitterbark** [comment]
But yes, I think it should be required to stay in the same wk_dir in order to do this (as in overwrite=true). This is for development, running the same thing over and over again in order to tweak/debug so I think it is normal to have overwrite=true. 

The only reason to use a new wk_dir is to start from a clean slate, so in that case the pre-processor should *not* use previously made files.  There could be a warning if you set overwrite=false and --no-file-rw=true, that it isn't going to do anything.
