### ISSUE TITLE
Merge GFDL-specific branch into main dev branch

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#44]
As part of the beta-4 release, targeting a consolidation of the GFDL-specific branch into a single code base.

This also depends on #40.

**Comment by tsjackson-noaa** [comment]
Closing this issue since it has been implemented as of the [v3.0 beta 3](https://github.com/NOAA-GFDL/MDTF-diagnostics/releases/tag/v3.0-beta.3) release. See PR NOAA-GFDL/MDTF-diagnostics#147.
