### ISSUE TITLE
Parsing file metadata error

### ISSUE THREAD

**Issue by erileydellaripa** [NOAA-GFDL/MDTF-diagnostics#460]
**Bug Severity**  
* [x ] **1 = Minor problem** that does not affect total framework functionality (e.g., computation error in a POD, problem with logging output, or an issue on a single system  
* [ ] **2 = Major problem** that affects overall functionality, but that does not occur for all users (e.g., problems installing the framework with a specific Conda version, a framework option that causes one or more PODs to fail, or missing/incompatible Python modules).  
* [ ] **3 = Catastrophic problem** that occurs frequently for multiple users and/or on multiple systems (e.g.,framework consistently fails to install on multiple systems, or one or more PODs continuously fails after running successfully) 

**Describe the bug**
Error while preprocessing a model file to check the metadata when running a test POD. If the "--disable-preprocessor flag" is used, there is no error. The variable (TAUX) in the file did have to be changed from Nm-2 to Pa to fit with the standard TAUX units. The units and standard_names appear to be correct from my end, so I'm not sure why the error persists. 

**Steps To Reproduce**
- Forked the GFDL repository
- Made a new branch
- Installed the conda environments 
- Altered the MDTF-diagnostics/src/default_tests.jsonc file to reflect my paths
- Ran the test/sample case
- Made a new .jsonc file to reflect my new POD that started with the default_test.jsonc template
- Made a directory for the new POD in mdtf/MDTF-diagnostics/diagnostics/
- Altered the settings, rst, and html files
- Ran the framework without the --disable-preprocessor flag

**Environment**
Describe the system environment:
- OS: macOS 10.15.7
- Conda version: 22.11.1, conda-build version : 3.20.5, python 3.10.10
- branch name and link: https://github.com/erileydellaripa/MDTF-diagnostics/tree/feature/ocn_wave_modes

**Log information and/or terminal output**
Copy information from any output logs and/or the terminal that might help with debugging.

[avg_annual_cycle_1980-2018_TropFlux_tauxPa_EQ_130to260.nc.zip](https://github.com/NOAA-GFDL/MDTF-diagnostics/files/11402002/avg_annual_cycle_1980-2018_TropFlux_tauxPa_EQ_130to260.nc.zip)
[E3SM.LY04.Equator.0362-0400.TAUX.day.nc.zip](https://github.com/NOAA-GFDL/MDTF-diagnostics/files/11402011/E3SM.LY04.Equator.0362-0400.TAUX.day.nc.zip)
[E3SM.LY04.Equator.0362-0400.log](https://github.com/NOAA-GFDL/MDTF-diagnostics/files/11402019/E3SM.LY04.Equator.0362-0400.log)

**Comment by wrongkindofdoctor** [comment]
@erileydellaripa 

Your dataset exposed a bug in the xr_parser module thanks to the latitude dimension having a length of 1. I have fixed it, and  was able to run your POD to completion. Once the associated PR passes the CI testing, I will merge the bug fix into the main branch, and you can update your repos/branches when you are ready.
