### ISSUE TITLE
Multiple model cases/ensembles

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#49]
From @bitterbark:
"The blocking pod that I'm working on has the capability of comparing not only multiple model cases but also multiple ensembles, showing the mean and the spread. Since the MDTF does not currently have that capability, I plan to implement it in a variation that only reads one model case. However, I would like to leave the other capabilities available for when the MDTF can do it. Can you tell me if you have a design in mind for including more cases, and/or ensembles, so I can move in that direction?"

**Comment by tsjackson-noaa** [comment]
Hi @bitterbark , 
This is definitely something that should be on our feature roadmap, as you've brought it up previously in calls. At this point I can't commit to anything, but I think the most natural way to accommodate ensemble data would be to extend the framework's naming convention for local data: something like `<casename>.<frequency>.<member number>.nc`. When your POD looks for data files, if it doesn't find the ensemble member number in the filename, it could treat the data as an ensemble with one member and use the same code path.

Considering multiple model cases is a thornier issue, as that breaks the framework's current design assumptions: namely, that the framework is essentially called separately for each case (since we need to do data search and preprocessing for each case before the PODs are run) and each run of a POD is independent (they don't persist data between invocations.)

**Comment by bitterbark** [comment]
Great idea on the optional ensemble member numbers. That should be easy for me to implement.

As for model cases, the incoming AMOC POD has an easy way of dealing with it. It runs independently over each model case into a unique working directory, and then checks if there are other cases availble to plot. If so, it produces a 'summary' html file in addition to the one for the individual cases.[http://www.cgd.ucar.edu/cms/bundy/Projects/diagnostics/mdtf/mdtf_figures/AMOC/MDTF_GFDL-CM2p1/AMOC_3D_Structure/AMOC/MDTF_GFDL-CM2p1/AMOC_3D_Structure/AMOC_3D_Structure_Summary.html](http://www.cgd.ucar.edu/cms/bundy/Projects/diagnostics/mdtf/mdtf_figures/AMOC/MDTF_GFDL-CM2p1/AMOC_3D_Structure/AMOC/MDTF_GFDL-CM2p1/AMOC_3D_Structure/AMOC_3D_Structure_Summary.html)

**Comment by andrewgettelman** [comment]
I don't think we should specify ensemble members. I think it should be more flexible. Dani and I were talking, and I think we should just have the case names as an array, not just a single value. PODs that are built that take a single value would just get array element zero, while the others can get the complete array.

This is how we have done things in the past, and I think is an easy path forward.

Then it could be an ensemble or different cases. There may also be other ways to specify ensemble members (Dani and I discussed this). 

We also could use this as a path forward to allow existing pods to loop over these names, produce plots and arrange them on a multiple web page. 

Thoughts?

**Comment by bitterbark** [comment]
Regarding ensembles, assuming we have a list of multiple cases, we could have an optional attribute ensemble_name = string. Any pod that handles ensembles can check this, and group cases together accordingly. Any other pod can just treat them as individual cases.  I can implement this in Rich Neale's blocking pod as an example of how to do it (with the group's approval on methodology).
