### ISSUE TITLE
Diagnostics doesn't work with recent update in "pydantic" library.

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#491]
### Discussed in https://github.com/NOAA-GFDL/MDTF-diagnostics/discussions/490

<div type='discussions-op-text'>

<sup>Originally posted by **hanjunkim0617** October 26, 2023</sup>
Hello everyone.

I'm now testing the diagnostics in various environment, 
and finding that diagnostic does not work with recent update in "pydantic" library.

For me, it was solved if I downgrade the "pydantic" in _MDTF_base environment as below.

conda activate _MDTF_base
conda install -c conda-forge pydantic==1.10.12

screenshots for error are attached.

Best regards,
Hanjun

[error.pdf](https://github.com/NOAA-GFDL/MDTF-diagnostics/files/13180656/error.pdf)

</div>

**Comment by wrongkindofdoctor** [comment]
Hi, @hanjunkim0617. I've moved this conversation to an issue. Could you please provide some more information:
-the OS you are using
-the branch you are working with, and the version of the package if you have checked out a specific tag. 



Note that I am working on upgrading the environments to python 3.11, and a adding support for environment installation with micromamba to improve performance. The upgrade may solve the pydantic issue as several of the package versions will be changed in the base and python environments. I'll notify you when the updates are ready to merge if you want to try them yourself.

**Comment by hanjunkim0617** [comment]
Hello!

I'm using the cluster with Ubuntu 20.04.6 LTS,
For the branch, I tried with "main" and "feature/runoff_sensitivities".
"feature/runoff_sensitivities" is the new branch in which I'm working on adding new diagnostics.
The errors are the same regardless of the branch.

I'm happy to try again if the new version comes out:)

Thank you!
Best regards,
Hanjun

**Comment by wrongkindofdoctor** [comment]
@hanjunkim0617 I've merged the updates into the main branch. Please sync your branches, rebuild the environments, and let me know if you have any more problems.
