### ISSUE TITLE
Py3 compatibility

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#5]
Specific todos:
- `from __future__ import print`
- try/catch blocks for renamed modules
- `range()` vs. `xrange()`
- Unicode strings in filesystem interaction, eg. `os.getcwd`
- Others? Need to use [six](https://pypi.org/project/six/)?

**Comment by jkrasting** [comment]
Do any of the imported modules have any issues moving to Python v3?

**Comment by tsjackson-noaa** [comment]
@jkrasting : sorry to have taken so long to get back to you! The only POD using python for computations (instead of as a wrapper that calls scripts in another language) is convective_transition_diag. I'll have to go through that in detail when I get to the py2->py3 migration.

**Comment by tsjackson-noaa** [comment]
Py3 features relevant for us (putting this here as a note to self):
- subprocess -> asyncio (the big one)
- subTest in unittest for defining sets of tests
- enum library for input validation
- pathlib for better path munging
- f-strings for more convenient string formatting

**Comment by jkrasting** [comment]
No worries, @tsjackson-noaa.

**Comment by tsjackson-noaa** [comment]
Belatedly documenting progress on this issue.

Framework code in /develop is py3-compatible as of d35fae3eb9285aecac0e6874d92715fe29508cd4 , with additional bug fixes in 2cf0ecfcb65e80576fdf167337f5bbe64ff98dee. This is included in /main and the 3.0 beta 2 release.

The base [conda environment](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/170226663a52d05fb02f9f6d5c426e6042317a5b/src/conda/env_python3_base.yml) for Python-based PODs has been updated to python 3. Currently no PODs in /develop run in this environment.

The Python3 migration was done in an experimental branch, before a python 3 migration policy had been adopted. The experimental branch (and the current framework code) used the [six](https://github.com/benjaminp/six) compatibility library for simultaneous py2- and py3-compatiblity in the same code base.

This requirement is unnecessary, since the framework code now runs in its own [conda environment](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/170226663a52d05fb02f9f6d5c426e6042317a5b/src/conda/env_base.yml), and maintaining simultaneous py2- and py3-compatibility would mean that the framework couldn't benefit from py3-only features. Future work will remove the use of six.py and transition the framework to a py3-only code base.

**Comment by jkrasting** [comment]
Excellent - thanks @tsjackson-noaa!

**Comment by tsjackson-noaa** [comment]
Closing this issue, as python 3 migration has been implemented and tested as described in my note from Aug 14th.
