### ISSUE TITLE
Error loading data for my POD

### ISSUE THREAD

**Issue by csyhuang** [NOAA-GFDL/MDTF-diagnostics#514]
**Bug Severity**  
* [x] **1 = Minor problem** that does not affect total framework functionality (e.g., computation error in a POD, problem with logging output, or an issue on a single system  
* [ ] **2 = Major problem** that affects overall functionality, but that does not occur for all users (e.g., problems installing the framework with a specific Conda version, a framework option that causes one or more PODs to fail, or missing/incompatible Python modules).  
* [ ] **3 = Catastrophic problem** that occurs frequently for multiple users and/or on multiple systems (e.g.,framework consistently fails to install on multiple systems, or one or more PODs continuously fails after running successfully) 

**Describe the bug**
When I tried testing my POD by running `./mdtf`, I encountered error at the data preparation stage and wonder how I can debug this. I was running from my branch:

https://github.com/csyhuang/MDTF-diagnostics/tree/finite_amplitude_wave_diag

After I executed:

```bash
./mdtf -f src/default_finite_amplitude_wave_diag.jsonc -v
```

I encountered the following error at the data preparation stage:
```
Received event while preprocessing <#MKNN:finite_amplitude_wave_diag.ta>: DataPreprocessEvent("Caught exception while cleaning attributes to write data for <#MKNN:finite_amplitude_wave_diag.ta>: ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()').")
```
The full log file can be found here: 

[GFDL-CM3_historical_r1i1p1.log](https://github.com/NOAA-GFDL/MDTF-diagnostics/files/14644938/GFDL-CM3_historical_r1i1p1.log)

The config files can be found at:
- https://github.com/csyhuang/MDTF-diagnostics/blob/finite_amplitude_wave_diag/src/default_finite_amplitude_wave_diag.jsonc
- https://github.com/csyhuang/MDTF-diagnostics/blob/finite_amplitude_wave_diag/diagnostics/finite_amplitude_wave_diag/settings.jsonc

On my own linux machine, I put the model data at (below are the relative paths):
```
mdtf/inputdata/model/GFDL-CM3_historical_r1i1p1/day/GFDL-CM3_historical_r1i1p1.ua.day.nc
mdtf/inputdata/model/GFDL-CM3_historical_r1i1p1/day/GFDL-CM3_historical_r1i1p1.va.day.nc
mdtf/inputdata/model/GFDL-CM3_historical_r1i1p1/day/GFDL-CM3_historical_r1i1p1.ta.day.nc
```

which were downloaded from:
```
ftp://nomads.gfdl.noaa.gov/1/CMIP5/output1/NOAA-GFDL/GFDL-CM3/historical/day/atmos/day/r1i1p1/v20120227/ua/ua_day_GFDL-CM3_historical_r1i1p1_20050101-20051231.nc
ftp://nomads.gfdl.noaa.gov/1/CMIP5/output1/NOAA-GFDL/GFDL-CM3/historical/day/atmos/day/r1i1p1/v20120227/va/va_day_GFDL-CM3_historical_r1i1p1_20050101-20051231.nc
ftp://nomads.gfdl.noaa.gov/1/CMIP5/output1/NOAA-GFDL/GFDL-CM3/historical/day/atmos/day/r1i1p1/v20120227/ta/ta_day_GFDL-CM3_historical_r1i1p1_20050101-20051231.nc
```

This is my python environment file:
https://github.com/csyhuang/MDTF-diagnostics/blob/finite_amplitude_wave_diag/src/conda/env_finite_amplitude_wave_diag.yml

**Environment**
Describe the system environment:
- Linux
- Conda info:
```
     active environment : _MDTF_finite_amplitude_wave_diag
    active env location : /home/clare/miniconda3/envs/_MDTF_finite_amplitude_wave_diag
            shell level : 2
       user config file : /home/clare/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=12.0=0
                          __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/clare/miniconda3  (writable)
      conda av data dir : /home/clare/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/clare/miniconda3/pkgs
                          /home/clare/.conda/pkgs
       envs directories : /home/clare/miniconda3/envs
                          /home/clare/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.28.1 CPython/3.7.6 Linux/4.15.0-214-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

---

May you advice how I can proceed? Thanks!

Clare

**Comment by wrongkindofdoctor** [comment]
@csyhuang Thank you for your patience. @jtmimns and I were able to identify the source of the preprocessor error and run your POD. There seem to be issues with the POD itself, so you'll need to debug it with the processed data files. Please merge the main branch updates into your development branch, and let us know if need more assistance.

**Comment by csyhuang** [comment]
Hi Jess @wrongkindofdoctor and Jacob @jtmims , thank you for fixing the preprocessor issue! After merging your new commits and fixing a file path issue on my side, I was able to run my POD end-to-end (finally!) with the plots on the html page 🤩 ! I will wrap up a code to submit a pull request soon!
