### ISSUE TITLE
Add Eulerian storm tracker

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#52]
Issue thread to document progress on incorporating/maintaining the Eulerian storm tracker POD; cc @jeyavinoth and @jfbooth. Associated pull request is #50.

**Comment by tsjackson-noaa** [comment]
Hi @jeyavinoth, so far the model plots look good!

- Please point me to where I can download the obs data (better to email me than to make this info public) so I can verify the other plots.
- [plotter.plot](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/d093d0be35cd272937de3ec66135ab8409d2bba3/diagnostics/eulerian_storm_track/plotter.py#L60)'s contour plots have a seam at lon=0. You may wish to consider using [cartopy.util.add_cyclic_point](https://stackoverflow.com/questions/50089485/seam-where-longitude-wraps-around-in-matplotlib-cartopy-mollweide-projection) to fix this.

**Comment by jeyavinoth** [comment]
Thanks @tsjackson-noaa 

- I sent you an email with a dropbox link to the obs_data used to create the plots. 
- I got rid of the seam at lon=0 using your suggestion. I pushed the changes to my fork.

**Comment by tsjackson-noaa** [comment]
@jeyavinoth - thanks for the updates. Everything looks great!

**Comment by jkrasting** [comment]
Glad the initial tests look good @tsjackson-noaa and @jeyavinoth - we still need to a do a test inside the firewall on GFDL data though.

**Comment by jkrasting** [comment]
@tsjackson-noaa - any updates on the internal testing?

**Comment by jeyavinoth** [comment]
@jkrasting @tsjackson-noaa Do you have any further updates on the internal testing?

**Comment by tsjackson-noaa** [comment]
The branch containing existing development work on this POD has been renamed from pod/eulerian-storm-track to [feature/add_eulerian_storm_track](https://github.com/NOAA-GFDL/MDTF-diagnostics/tree/feature/add_eulerian_storm_track), as part of the reorganization proposed in issue NOAA-GFDL/MDTF-diagnostics#106.
