### ISSUE TITLE
MDTF Diagnostics 4.0?

### ISSUE THREAD

**Issue by nishsilva** [NOAA-GFDL/MDTF-diagnostics#543]
Is v4.0.alpha updated in the git repository? It seems that previous MDTF documentation has been replaced with MDTF 4.0 documentation. But when I check v4.0.alpha tag it says it is unavailable. Can someone clarify this?

**Comment by wrongkindofdoctor** [comment]
@nishsilva I'm still updating the docs and need to debug some issues that arose from functionality testing with the GFDL convention. I will tag the repo by the end of the week. In the meantime, you can begin working with the main branch if you wish--it has all of the new preprocessor features and has passed basic testing CMIP data on RHEL8, Windows Subsystem for Linux, and MacOS Sonoma.

**Comment by nishsilva** [comment]
> @nishsilva I'm still updating the docs and need to debug some issues that arose from functionality testing with the GFDL convention. I will tag the repo by the end of the week. In the meantime, you can begin working with the main branch if you wish--it has all of the new preprocessor features and has passed basic testing CMIP data on RHEL8, Windows Subsystem for Linux, and MacOS Sonoma.

Great! Thank you.
