### ISSUE TITLE
Enable Travis CI on this repository

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#55]
Travis tests are currently running on @tsjackson-noaa 's fork.  Need to enable integration for this repository.

**Comment by tsjackson-noaa** [comment]
Believe this should be straightforward: I haven't set any config in my Travis account beyond what's in the repo's [config file](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/main/.travis.yml), and multiple travis accounts pulling the same repo won't block each other. The badge on README.md will need to be changed.

**Comment by tsjackson-noaa** [comment]
@jkrasting : Badge is configured correctly and it looks like CI is running successfully on commits we've pushed since then. If there's nothing more to do to set up Travis, feel free to close this issue.

**Comment by jkrasting** [comment]
Thanks @tsjackson-noaa
