### ISSUE TITLE
Enable readthedocs webhooks

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#56]
Migrate readthedocs documentation to this repository.  @tsjackson-noaa - can you take a look and see what needs to be done for this task?

**Comment by tsjackson-noaa** [comment]
@jkrasting : sent you an email with my account config info, although that's probably not sensitive. Believe there should be no obstacles to the transfer -- if I delete the repo from my RTD account, that should free up the current URL for your use, and then docs will be build reproducibly.

**Comment by jkrasting** [comment]
@tsjackson-noaa - I did see your email.   I didn't get to the readthedocs updates yet, but it's on my to-do list.  Hopefully tomorrow.

**Comment by tsjackson-noaa** [comment]
@jkrasting : Thanks for making the transition -- went through all the links and PDFs and the build appears identical to what it was in the old account. If everything's OK with the readthedocs setup, feel free to close this issue.

**Comment by jkrasting** [comment]
Thanks @tsjackson-noaa
