### ISSUE TITLE
Requesting example POD test case for docker with preprocessor updates

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [NOAA-GFDL/MDTF-diagnostics#609]
I am looking for a test config file (with catalogs/pointers to associated datasets) to run "example" single-run POD as I test the docker container that uses the current main branch. This will likely also help with the overall POD testing with preprocessor so I can provide feedback. 
Note that the current main is just used for testing now, and the updates will be in sync with the future tagged release. If I need to be using something else that's not main for "example POD" testing with catalogs, let me know. 

If there is a synthetic test case, I can start from there. But, anything else appreciated too.

**Comment by wrongkindofdoctor** [comment]
@aradhakrishnanGFDL The test config files have not been updated yet. I'd suggest following the [quickstart instructions ](https://github.com/wrongkindofdoctor/MDTF-diagnostics/tree/main?tab=readme-ov-file#5-run-the-framework) to generate a synthetic dataset for your desired time period and modify the paths in the example_multicase catalog and json header file to point to the appropriate paths on your machine/in the container. You can then modify one of the template/runtime_config files to run the example POD with just one case.

**Comment by aradhakrishnanGFDL** [comment]
I started off with CMIP synthetic, but then there were a few issues, I thought perhaps a GFDL synthetic test case was relevant to the current updates. What do you think? 
GFDL synthetic data with the pip install only generated a few daily data, no TAS :( I will open a separate issue on this one.

@jtmims can you pass me the AM5 test config where the example POD worked? That would be helpful. 

Single example POD seems to require an OBS dataset, and I also got stuck there.

**Comment by jtmims** [comment]
Hi @aradhakrishnanGFDL! I am also currently running into some issues with the example pod on the latest commit. We re-implemented some functions that reconcile the framework knowledge with what is in the dataset. I will try and fix this real quick. I will also send over an email showing you the path to test config.

**Comment by aradhakrishnanGFDL** [comment]
closing this. Thanks @jtmims for the synthetic test-case running the example_mulitcase POD.
