### ISSUE TITLE
help option in MDTF

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [NOAA-GFDL/MDTF-diagnostics#671]
The --help option does not seem to work

./mdtf --help

/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/basic.py:589: SyntaxWarning: invalid escape sequence '\_'
  """Splice sub-lists (values of *splice_d*) into list *list_* after their
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:139: SyntaxWarning: invalid escape sequence '\_'
  """Match *str\_* using Python :py:func:`re.fullmatch` with *regex* and
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:300: SyntaxWarning: invalid escape sequence '\s'
  """Class which takes an 'or' of multiple :class:`RegexPattern`\s, to parse
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:775: SyntaxWarning: invalid escape sequence '\_'
  """Create an object instance from a string representation *str\_*.
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:793: SyntaxWarning: invalid escape sequence '\='
  """Return a dict of the subset of fields or entries in *d* that correspond to
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:836: SyntaxWarning: invalid escape sequence '\='
  """Given a dataclass *dc* (may be the class or an instance of it), and a dict,

**Comment by wrongkindofdoctor** [comment]
I can't replicate this issue on my mac or workstation using the latest main branch. Is this occurring in the container?

**Comment by aradhakrishnanGFDL** [comment]
> @aradhakrishnanGFDL I can't replicate this issue on my mac or workstation using the latest main branch. Is this occurring in the container?

no its not in the container. Can you paste what you see?

**Comment by aradhakrishnanGFDL** [comment]
Yesterday, it just hung after the series of warnings. 
Today, the commit hash 4cbb6bec010ea81 from Aug 20 and the MDTF central installation shows this..

what do you think about suppressing the warnings here? They also show up in my actual runs. let me know if you see something else.

```
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/basic.py:589: SyntaxWarning: invalid escape sequence '\_'
  """Splice sub-lists (values of *splice_d*) into list *list_* after their
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:139: SyntaxWarning: invalid escape sequence '\_'
  """Match *str\_* using Python :py:func:`re.fullmatch` with *regex* and
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:300: SyntaxWarning: invalid escape sequence '\s'
  """Class which takes an 'or' of multiple :class:`RegexPattern`\s, to parse
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:775: SyntaxWarning: invalid escape sequence '\_'
  """Create an object instance from a string representation *str\_*.
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:793: SyntaxWarning: invalid escape sequence '\='
  """Return a dict of the subset of fields or entries in *d* that correspond to
/home/oar.gfdl.mdtf/mdtf/MDTF-diagnostics/src/util/dataclass.py:836: SyntaxWarning: invalid escape sequence '\='
  """Given a dataclass *dc* (may be the class or an instance of it), and a dict,
Usage: MDTF-diagnostics [OPTIONS]

  A community-developed package to run Process Oriented Diagnostics on weather
  and climate data

Options:
  -v, --verbose          Enables verbose mode.
  -f, --configfile PATH  Path to the runtime configuration file  [required]
  --help                 Show this message and exit.
```

**Comment by wrongkindofdoctor** [comment]
There isn't a problem with --help; the message you're seeing is just a warning about the comment formatting that is coming from Python, not us. I'll clean the comments up in the next round of fixes.
