### ISSUE TITLE
Global POD realm setting not being parsed correctly

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#681]
**Bug Severity**  
* [ ] **1 = Minor problem** that does not affect total framework functionality (e.g., computation error in a POD, problem with logging output, or an issue on a single system  
* [x] **2 = Major problem** that affects overall functionality, but that does not occur for all users (e.g., problems installing the framework with a specific Conda version, a framework option that causes one or more PODs to fail, or missing/incompatible Python modules).  
* [ ] **3 = Catastrophic problem** that occurs frequently for multiple users and/or on multiple systems (e.g.,framework consistently fails to install on multiple systems, or one or more PODs continuously fails after running successfully) 

**Describe the bug**
The framework expects a global POD realm entry in the pod_env_vars section of the settings file when it should be parsing the data section.

**Steps To Reproduce**
What steps did you follow to produce the bug

**Environment**
Describe the system environment:
- OS: RHEL 8
- Conda version: [the `conda info` command will provide the installation information] 
- branch name and link: [e.g., develop, https://github.com/NOAA-GFDL/MDTF-diagnostics/tree/develop]

**Log information and/or terminal output**
Copy information from any output logs and/or the terminal that might help with debugging.

**Comment by erileydellaripa** [comment]
Thanks for fixing these issues, @wrongkindofdoctor. I was able to use my static land_area_fraction variable.
