### ISSUE TITLE
Missing FTP links in README file

### ISSUE THREAD

**Issue by Wen-hao-Dong** [NOAA-GFDL/MDTF-diagnostics#7]
The links for _Latest code, Pre-digested observational data, NCAR-CESM-CAM, and NOAA-GFDL-CM4_ under **Downloading and Running** section are missing. All of them are ftp links which are not supported with github markdown. Should we write out the links so the users can easily copy them into their ftp client?

**Comment by tsjackson-noaa** [comment]
Good idea -- will copy the written-out links from the develop branch.

**Comment by tsjackson-noaa** [comment]
Writing a note because I just discovered this feature: you can automatically close github issues by putting a link in your commit message: https://help.github.com/en/articles/closing-issues-using-keywords
Github will then close the issue with a link to your fix, like what happened above.
