### ISSUE TITLE
Create coarse resolution input data for testing

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MDTF-diagnostics#71]
Thinking more about our mini-leads call earlier this week and our need for coarse-resolution input data for testing.  I would like to spend some time trying to create a 10x10-degree input dataset either through averaging, or downsampling as @andrewgettelman proposed.

@tsjackson-noaa, @yihungkuo, @wrongkindofdoctor, @Wen-hao-Dong - is there a master list of variables and their time resolutions that are used by all PODs in the package thus far?

**Comment by jkrasting** [comment]
I was able to condense our roughly **17 GB** of model test data down to **185 MB**.  Here is a package I wrote to subsample the data to 15ºx15º grid:

https://github.com/jkrasting/mdtf_data_decimator

Some facts:
- the default test cases ran and produced semi-reasonable plots with the only exception being failures from the Wheeler-Kiladis POD
- the MJO Propagation POD ran in 13.4 seconds on the reduced resolution CM4 data
- the remaining PODs ran in 44.5 seconds for the QBOi data

This seems tractable for running all of the MDTF test cases on an external CI system such as Travis or GitHub Actions.  

Here is a tar file with all of the coarse resolution jobs:
```
ftp://ftp.gfdl.noaa.gov/pub/John.Krasting/mdtf/model.NCAR-GFDL.reduced.tar.gz
```

@wrongkindofdoctor, @tsjackson-noaa, @bitterbark, @yihungkuo - Can you please try out this dataset on the GFDL, NCAR, and UCLA systems?

**Comment by tsjackson-noaa** [comment]
Wow, I'm surprised everything worked so well on such coarse data! The current dataset used for Travis testing (ftp://ftp.gfdl.noaa.gov/pub/thomas.jackson/travis_test.tar) is **443mb** and only contains monthly data from the new NCAR timeslice run (and obs data, but that's negligible in comparison).

This will definitely be a big plus for outside-the-firewall CI! I'll update the Travis test suite to use this data. Any PODs that break on coarse data (I'm thinking of Jimmy Booth's storm tracker) can be excluded from the test suite.

**Comment by jkrasting** [comment]
Turns out that part of the Wheeler-Kiladis errors (#74) were due to going too far in coarsening.  I created a new coarse resolution dataset where the daily data were coarsened to 5ºx5º.   I made up for some of the increased data volume by further coarsening the remaining datasets to 20ºx20º.  See:

```
ftp://ftp.gfdl.noaa.gov/pub/John.Krasting/mdtf/model.NCAR-GFDL.reduced.20201125.tar.gz
```

I tried out the remaining test cases.  One new error that cropped up was in the `convective_transition_diag`:

```
**************************************************
Excuting Convective Transition Critical Collapse (convecTransCriticalCollapse.py)......
**************************************************
Load user-specified binning parameters... ...Loaded!
Binned output detected...
   Loading /Users/krasting/mdtf/wkdir/MDTF_QBOi.EXP1.AMIP.v9.001_1977_1981/convective_transition_diag/model/netCDF/QBOi.EXP1.AMIP.001.convecTransBasic_tave.nc
   Loading /Users/krasting/mdtf/inputdata/obs_data/convective_transition_diag/convecTransBasic_R2TMIv7r1_200206_201405_res=0.25_fillNrCWV_tave.nc
Binned output Loaded!
Starting fitting procedure... ...Fitted!
Plotting...
   Plotting OBS Figure... ...Completed!
      OBS Figure saved as /Users/krasting/mdtf/wkdir/MDTF_QBOi.EXP1.AMIP.v9.001_1977_1981/convective_transition_diag/obs/PS/convecTransCriticalCollapse_stats_R2TMIv7r1_200206_201405_res=0.25_fillNrCWV_tave.eps!
      OBS Figure saved as /Users/krasting/mdtf/wkdir/MDTF_QBOi.EXP1.AMIP.v9.001_1977_1981/convective_transition_diag/obs/PS/convecTransCriticalCollapse_wc_R2TMIv7r1_200206_201405_res=0.25_fillNrCWV_tave.eps!
   Plotting MODEL Figure...
Traceback (most recent call last):
  File "/Users/krasting/mdtf/MDTF-diagnostics/diagnostics/convective_transition_diag/convecTransCriticalCollapse.py", line 123, in <module>
    params_data["args3"],params_data["plot_params"])
  File "/Users/krasting/mdtf/MDTF-diagnostics/diagnostics/convective_transition_diag/convecTransCriticalCollapse_util.py", line 722, in convecTransCriticalCollapse_plot
    PDFNormalizer=pdf[reg,numpy.where(cwv_bin_center<=wc[reg,Tidx])[0][-1],Tidx]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by jkrasting** [comment]
There is now a fully-synthetic version of the test data.  I updated the name of the previously referenced git repo to [`mdtf_test_data`](https://github.com/jkrasting/mdtf_test_data) to reflect the added scope.  See:  https://github.com/jkrasting/mdtf_test_data

The synthetic data are generated by randomly sampling a normal distribution based on means and standard deviations obtained from the original data.  In the case of 3D-data, separate means/sigmas are used for each individual level. 

If you install/update the package, there are two new scripts that will generate synthetic data that look like NCAR CESM2 and GFDL CM4 output:

To generate NCAR CESM output in a directory called `NCAR.Synthetic`:
```
./ncar_synthetic.py
```

To generate GFDL CM4 output in a directory called `GFDL.Synthetic`:
```
./gfdl_synthetic.py
```

Clearly a normal distribution may not be ideal for every field (e.g. precipitation), but the goal of this dataset is to test code flow.  Many opportunities exist for improvement.  @tsjackson-noaa - I believe you started on something last fall along these lines?  Are there some convergence opportunities here?

Since the files are inherently devoid of any temporal variability, it's interesting to look at the resulting figures from the MDTF to see what world with no variability looks like in these diagnostics.

@wrongkindofdoctor - perhaps we can work this into the CI testing.

@yihungkuo - the convective transition POD also fails on this data. We need to come up with something special for that POD
