### ISSUE TITLE
Update documentation to clarify developer responsibilities and add git rebase instructions

### ISSUE THREAD

**Issue by wrongkindofdoctor** [NOAA-GFDL/MDTF-diagnostics#72]
The documentation should explicitly state that developers should 
1) submit PRs to the develop branch
2) ensure that their branches are up-to-date with develop with all merge conflicts resolved
3) frequently sync their branches with develop to avoid large merge conficts

It should also include instructions for rebasing branches onto the target branches to streamline the commit history.

**Comment by tsjackson-noaa** [comment]
Closing this issue, since PR #83 was merged.
