### ISSUE TITLE
Error when combining POD with the MDTF framework 

### ISSUE THREAD

**Issue by chiaweh2** [NOAA-GFDL/MDTF-diagnostics#73]
This is for POD tropical_pacific_sea_level #70 . Currently, the POD is working fine when execute in my local server with the Conda env set to _MDTF_python3_base through `python pod.py` (meaning execute through python directly not incorporate with the framework). However, I am not able to successfully make it work by doing `./mdtf -f src/default_cesm2.jsonc` (the .jsonc I created). I am guessing there is something wrong in the `setting.jsonc` or` default_cesm2.jsonc`. I also create a fieldlist file for OMIP_CESM (`fieldlist_OMIP_CESM2.jsonc`). 

The error message is posted below and happened when I execute ` ./mdtf -f src/default_cesm2.jsonc`. 

`- _unittest: false`
`  CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics`
`Traceback (most recent call last):`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 319, in <module>
    mdtf = MDTFFramework(code_root, defaults_rel_path)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 60, in __init__
    self._framework_init(code_root, defaults_rel_path)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 82, in _framework_init
    self.parse_mdtf_args(cli_obj, config)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 114, in parse_mdtf_args
    self.parse_paths(cli_obj, config)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 207, in parse_paths
    config.paths.parse(cli_obj.config, cli_obj.custom_types.get('path', []))`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util_mdtf.py", line 44, in parse
    self[key] = self._init_path(key, d, env=env)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util_mdtf.py", line 64, in _init_path
    util.coerce_from_iter(d[key]), root_path=self.CODE_ROOT, env=env`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util.py", line 427, in resolve_path
    path = os.path.expanduser(path) # resolve '~' to home dir`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)`
`TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by wrongkindofdoctor** [comment]
There is a problem with one of the paths defined in the custom json files for this POD. The settings.jsonc file doesn't have any file paths (though there could be an error with concatenating the file names to a path defined elsewhere).  The error occurs during initialization, so my guess is that it's having trouble parsing default_cesm2.jsonc. Maybe the conda_env_root needs a full path instead of './envs', or it's in  a different location (my envs directory path is $CONDA_ROOT/envs, for example). Tagging @jkrasting and @tsj5 in case they have more insight.

**Comment by chiaweh2** [comment]
Thanks @wrongkindofdoctor. I compared line by line between `default_test.jsonc` and `default_cesm2.jsonc`. I found that in the `default_cesm2.jsonc`  "OUTPUT_DIR" need to be set instead of leaving blank 

 ` // Directory to write output files. Defaults to working directory if blank.`
 ` "OUTPUT_DIR": "../wkdir",`

However, the error message has changed to 


`- _unittest: false`
`  CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics`
`Traceback (most recent call last):`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 319, in <module>
    mdtf = MDTFFramework(code_root, defaults_rel_path)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 60, in __init__
    self._framework_init(code_root, defaults_rel_path)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 84, in _framework_init
    self._post_parse_hook(cli_obj, config)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 212, in _post_parse_hook
    _ = util_mdtf.VariableTranslator()`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util.py", line 35, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util_mdtf.py", line 160, in __init__
    d = util.read_json(filename)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util.py", line 302, in read_json
    return parse_json(str_)`
`  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/util.py", line 307, in parse_json
    parsed_json = json.loads(str_, object_pairs_hook=collections.OrderedDict)`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())`
`  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)`
`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 13 column 3 (char 388)`

I have tried changing the "conda_env_root" to full path still shown the same error and I cannot seem to find the part that I did not used double quotes in all jsonc files.

**Comment by wrongkindofdoctor** [comment]
Hmmm, I can't find anything obviously wrong with the quotes anywhere. A potential error source is the [comma after the tauvo](https://github.com/chiaweh2/MDTF-diagnostics/blob/22405eeef2a505d0a1f25e53804e4c3158498fe8/src/fieldlist_OMIP_CESM2.jsonc#L17) in the var_names section in the fieldlist json, and/or the [comma after lon_max](https://github.com/chiaweh2/MDTF-diagnostics/blob/22405eeef2a505d0a1f25e53804e4c3158498fe8/diagnostics/tropical_pacific_sea_level/settings.jsonc#L46) in the settings json. The framework might see the commas and expect more variables, and thus produce an error that there is a missing property value.

**Comment by chiaweh2** [comment]
Wow, yes. The comma solves the error message. It seems to finally finish parsing the json file. 

Based on the standard output, all paths seem correct except the conda_root and related envs. I found the conda_root in some default files are cap and in some are lowercase. I have to set the conda_root to lowercase to make it parse that conda_root setting. The other related thing is the conda_env_root. It cannot seems to recognize relative path "./envs". I have to set it to full path manually. I cannot find place to control `venv_root` and `r_lib_root` and not sure if the error is due to this setting. 

Besides the path, there seems to be two PODLISTs. The first one is the one I set in `default_cesm2.jsonc`. The second one seems to be the original whole list and not including my pod name. Is there some place else I am missing on editing the pod list?

P.S. I am really sorry for these thread of different error messages. I tried debug and find answer from the readthedoc site, but cannot seems to find the solution. I hope it is not appropriate to discuss this here and thank you again for the help @wrongkindofdoctor 

```
- _unittest: false
  CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
Found /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
Found /storage1/home1/chiaweih/mdtf/inputdata/obs_data
Found /storage1/home1/chiaweih/mdtf/inputdata/model
Found /storage1/home1/chiaweih/mdtf/wkdir
Found /storage1/home1/chiaweih/mdtf/wkdir
DEBUG: SETTINGS:
- case_list(0): - CASENAME: CESM2_omip1_r1i1p1f1_gn
    model: CESM2
    convention: OMIP_CESM2
    FIRSTYR: 1948
    LASTYR: 2009
    CASE_ROOT_DIR: /storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/mon
    pod_list:
      tropical_pacific_sea_level
    experiment:
  pod_list:
    convective_transition_diag
    ENSO_MSE
    EOF_500hPa
    MJO_prop_amp
    MJO_suite
    MJO_teleconnection
    precip_diurnal_cycle
    SM_ET_coupling
    Wheeler_Kiladis
  paths: - CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
    MODEL_DATA_ROOT: /storage1/home1/chiaweih/mdtf/inputdata/model
    OBS_DATA_ROOT: /storage1/home1/chiaweih/mdtf/inputdata/obs_data
    OUTPUT_DIR: /storage1/home1/chiaweih/mdtf/wkdir
    WORKING_DIR: /storage1/home1/chiaweih/mdtf/wkdir
    conda_root:
    conda_env_root: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/envs
    venv_root: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/envs/venv
    r_lib_root: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/envs/r_libs
  settings: - data_manager: Local_File
    file_transfer_timeout: 300
    environment_manager: Conda
    verbose: 1
    convert_flags: -dSAFER -dBATCH -dNOPAUSE -dEPSCrop -r150 -sDEVICE=png16m -dTextAlphaBits=4 -dGraphicsAlphaBits=4
  envvars: - RGB: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/rgb
    MPLBACKEND: Agg

======= Starting /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py

Traceback (most recent call last):
  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/storage1/home1/chiaweih/anaconda2/envs/_MDTF_base/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 321, in <module>
    mdtf.main_loop()
  File "/storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py", line 287, in main_loop
    case.pods.append(pod)
UnboundLocalError: local variable 'pod' referenced before assignment
```

**Comment by wrongkindofdoctor** [comment]
After digging through the docs, I found this line in[ section 7.3](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_walkthrough.html):
> The framework reads the other parts of your POD’s settings.jsonc, e.g., pod_env_vars, 
> and generates additional environment variables accordingly (on top of those being defined through default_tests.jsonc).

So, both your POD list and the default_tests POD list are generated by default.
venv_root and r_lib_root are internal directories that the user shouldn't need to worry about, and don't seem to be causing the error. 

For some reason, your pod isn't being set, and I wonder if it also needs to be in the tests json list. Try adding your pod name to default_tests.jsonc pod list. 

I'll be sure to report the issues you've been having to the group, with a note to add clarification to the documentation about things like not leaving empty parentheses in the jsonc config files, case sensitivity of pathnames, etc... All of these issues could probably be resolved to improve the UX.

**Comment by chiaweh2** [comment]
@wrongkindofdoctor thanks again. I tried add my pod name to default_tests but it does not seem to work.  but could not find the place which indicates where I should add my pod besides the pod_list in default_xx.jsonc.

After some digging into the mdtf.py in /src. I found the assertion error is related to the [`pod = self.Diagnostic(pod_name)` ](https://github.com/NOAA-GFDL/MDTF-diagnostics/blob/f0661e612006d8b14b646f2fdb6fe900e690987f/src/mdtf.py#L284).

**Comment by jkrasting** [comment]
@chiaweh2 - it looks like there are a lot of syntax errors in `tropical_pacific_sea_level/settings.jsonc`  The framework is not catching this is an invalid `settings.jsonc` file.  I think if you clean up the syntax, you'll get past this error.

**Comment by chiaweh2** [comment]
@jkrasting Thank you! Yes there are syntex errors which I did not notice earlier and yes an error message pointing to the jsonc file which has bugs would be nice for debugging. 

After correcting the syntax, I have gotten past the error. Currently the framework seems to call my POD but not executing (I have some print commend at the very beginning of my POD main script but is not showing on the screen). Does this mean there are still some error in the jsonc file? Or this is saying the POD is not executed due to bugs in the POD. Is the standard output from POD execution stored somewhere else?

The error message seems to point me to missing output file which I don't quite understand since the standard output on the screen did not show any of my `print` commend so I assume the POD is not even executed yet.

```
(base) -bash-4.1$ ./mdtf -f src/default_cesm2.jsonc
- _unittest: false
  CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
Found /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
Found /storage1/home1/chiaweih/mdtf/inputdata/obs_data
Found /storage1/home1/chiaweih/mdtf/inputdata/model
Found /storage1/home1/chiaweih/mdtf/wkdir
Found /storage1/home1/chiaweih/mdtf/wkdir
DEBUG: SETTINGS:
- case_list(0): - CASENAME: CESM2_omip1_r1i1p1f1_gn
    model: CESM2
    convention: OMIP_CESM2
    FIRSTYR: 1948
    LASTYR: 2009
    CASE_ROOT_DIR: /storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/mon
    pod_list:
      tropical_pacific_sea_level
    experiment:
  pod_list:
    convective_transition_diag
    ENSO_MSE
    EOF_500hPa
    MJO_prop_amp
    MJO_suite
    MJO_teleconnection
    precip_diurnal_cycle
    SM_ET_coupling
    tropical_pacific_sea_level
    Wheeler_Kiladis
  paths: - CODE_ROOT: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics
    MODEL_DATA_ROOT: /storage1/home1/chiaweih/mdtf/inputdata/model
    OBS_DATA_ROOT: /storage1/home1/chiaweih/mdtf/inputdata/obs_data
    OUTPUT_DIR: /storage1/home1/chiaweih/mdtf/wkdir
    WORKING_DIR: /storage1/home1/chiaweih/mdtf/wkdir
    conda_root: /storage1/home1/chiaweih/anaconda2
    conda_env_root: /storage1/home1/chiaweih/anaconda2/envs
    venv_root: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/envs/venv
    r_lib_root: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/envs/r_libs
  settings: - verbose: 1
    data_manager: Local_File
    file_transfer_timeout: 300
    environment_manager: Conda
    save_ps: true
    save_nc: true
    convert_flags: -dSAFER -dBATCH -dNOPAUSE -dEPSCrop -r150 -sDEVICE=png16m -dTextAlphaBits=4 -dGraphicsAlphaBits=4
  envvars: - RGB: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/rgb
    MPLBACKEND: Agg

======= Starting /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py
/storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009.v6 created
Found /storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn
Calling query_dataset on zos @ 1mo
Calling query_dataset on tauuo @ 1mo
Calling query_dataset on tauvo @ 1mo
Found zos (= zos_var) @ 1mo for tropical_pacific_sea_level
Found tauuo (= tauuo_var) @ 1mo for tropical_pacific_sea_level
Found tauvo (= tauvo_var) @ 1mo for tropical_pacific_sea_level
Found /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/diagnostics/tropical_pacific_sea_level
Found /storage1/home1/chiaweih/mdtf/inputdata/obs_data/tropical_pacific_sea_level
/storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009.v6/tropical_pacific_sea_level created
Found /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/diagnostics/tropical_pacific_sea_level
Found /storage1/home1/chiaweih/mdtf/inputdata/obs_data/tropical_pacific_sea_level
Found /storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009.v6/tropical_pacific_sea_level
tropical_pacific_sea_level will run in env: _MDTF_python3_base
Calling : /usr/bin/env python -u /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/diagnostics/tropical_pacific_sea_level/tropical_pacific_sea_level.py

Failed to find file or connect to server.
Reason:  [Errno 2] No such file or directory: '/storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009.v6/tropical_pacific_sea_level/model/example_model_plot.png'

Failed to find file or connect to server.
Reason:  [Errno 2] No such file or directory: '/storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009.v6/tropical_pacific_sea_level/obs/example_obs_plot.png'
ERROR: tropical_pacific_sea_level has missing output files.
Exiting normally from /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/mdtf.py
```

**Comment by jkrasting** [comment]
Looks like some progress @chiaweh2.  At this stage, you should have some logs available in `mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009.v6/tropical_pacific_sea_level/`.  Would you be able to attach your log file here?  Is there anything obvious that you can see?

**Comment by chiaweh2** [comment]
@jkrasting  Thank you for the direction! I did find the output log and fixed the bug that is in my main script. The reason of the bug is mainly related to the environment variable that is supposed to be setup in the previous step seems to be missing. However, at the same time, I find another set of environment variable that almost represent the same time but with different environment variable name. 

The two main  environment variables missing is "MODEL_DATA_ROOT" and "OBS_DATA_ROOT" and what is actually working is "DATADIR" and "OBS_DATA". Maybe it is something that I setup wrong in jsonc again to make this error. 

After I corrected the above error, my script is working with the framework now with eps outputs. 

The log file is looking like this now.
```
--- MDTF.py Starting POD tropical_pacific_sea_level
Found files: 
/storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/mon/CESM2_omip1_r1i1p1f1_gn.zos.mon.nc
/storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/mon/CESM2_omip1_r1i1p1f1_gn.tauuo.mon.nc
/storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/mon/CESM2_omip1_r1i1p1f1_gn.tauvo.mon.nc
 Env vars: 
CASENAME: CESM2_omip1_r1i1p1f1_gn
DATADIR: /storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn
FIRSTYR: 1948
LASTYR: 2009
MPLBACKEND: Agg
Model_coord0: lat
Model_coord1: lon
Model_dim0: time
Model_dim1: nlat
Model_dim2: nlon
Model_legend_name: CESM2-CORE
Model_name: CESM2_CORE
Model_path: CESM2_omip1_r1i1p1f1_gn/mon/
OBS_DATA: /storage1/home1/chiaweih/mdtf/inputdata/obs_data/tropical_pacific_sea_level
POD_HOME: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/diagnostics/tropical_pacific_sea_level
RGB: /storage1/home1/chiaweih/mdtf/MDTF-diagnostics/src/rgb
WK_DIR: /storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009/tropical_pacific_sea_level
areacello_file: CESM2_omip1_r1i1p1f1_gn.areacello.mon.nc
date_int_offset: 0
fyear: 2009
lat_coord: lat
lat_coord_bnds: lat_bnds
lat_max: 20
lat_min: 10
lev_coord: lev
lev_coord_bnds: lev_bnds
lon_coord: lon
lon_coord_bnds: lon_bnds
lon_max: 150
lon_min: 120
model: CESM2
pressure_to_Pa_factor: 1
syear: 1993
tauuo_conversion_factor: 1
tauuo_file: CESM2_omip1_r1i1p1f1_gn.tauuo.mon.nc
tauuo_var: tauuo
tauvo_conversion_factor: 1
tauvo_file: CESM2_omip1_r1i1p1f1_gn.tauvo.mon.nc
tauvo_var: tauvo
time_coord: time
time_coord_bnds: time_bnds
variab_dir: /storage1/home1/chiaweih/mdtf/wkdir/MDTF_CESM2_omip1_r1i1p1f1_gn_1948_2009
zos_conversion_factor: 1
zos_file: CESM2_omip1_r1i1p1f1_gn.zos.mon.nc
zos_var: zos
 --- MDTF.py calling POD tropical_pacific_sea_level

_CONDA_EXE=/storage1/home1/chiaweih/anaconda2/bin/conda
_CONDA_ROOT=/storage1/home1/chiaweih/anaconda2
Found program python3.
--------------------------
Start reading set parameter (pod_env_vars)
--------------------------
--------------------------
Start processing model outputs
--------------------------
read CESM2_CORE tauuo
/storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/../CESM2_omip1_r1i1p1f1_gn/mon/CESM2_omip1_r1i1p1f1_gn.tauuo.mon.nc
read CESM2_CORE tauvo
/storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/../CESM2_omip1_r1i1p1f1_gn/mon/CESM2_omip1_r1i1p1f1_gn.tauvo.mon.nc
read CESM2_CORE zos
/storage1/home1/chiaweih/mdtf/inputdata/model/CESM2_omip1_r1i1p1f1_gn/../CESM2_omip1_r1i1p1f1_gn/mon/CESM2_omip1_r1i1p1f1_gn.zos.mon.nc
read WASwind tx
read WASwind ty
read CMEMS adt
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.

```
