### ISSUE TITLE
Handle code dependencies with git-subtree instead of git-submodule

### ISSUE THREAD

**Issue by tsjackson-noaa** [NOAA-GFDL/MDTF-diagnostics#87]
The CMIP6 [CMOR tables](https://github.com/PCMDI/cmip6-cmor-tables) are currently included in the code base as a submodule, in order to keep these sources of reference information up-to-date. This means that downstream users need to remember to run `git submodule update` when pulling in changes, and has already been the source of merge conflicts in pull requests.

@jkrasting suggested that we consider doing this with [git-subtree](https://manpages.debian.org/testing/git-man/git-subtree.1.en.html), which appears to solve this problem and makes things more transparent to users. Other info (via a quick google search): [post #1](https://www.atlassian.com/git/tutorials/git-subtree), [post #2](https://www.sourcefield.nl/post/git-subtree-survival-tips/). We should investigate this further.

If we wind up implementing this, references to `git submodule` in the user-facing [documentation](https://mdtf-diagnostics.readthedocs.io/en/latest/sphinx/dev_git_intro.html) will need to be changed.

**Comment by jkrasting** [comment]
This could simplify the checkout process.  

Ideally, however, git-subtree is more intended for situations where active development is also occurring in the sub-repository.

**Comment by tsjackson-noaa** [comment]
I submitted a PR (linked) that replaces the CMOR tables submodule with a subtree.

I'm in favor of implementing this change on the grounds that it simplifies the contributor experience: no submodules means fewer git commands to remember, and it eliminates a source of merge conflicts in PRs that we already encountered. The only disadvantage I'm aware of is that we'll receive all commits to cmip6-cmor-tables going forward, and that that's still being updated pretty frequently (in a backwards-compatible way, ie I think they're just adding new institution_ids, etc. to keep up with the data as it's published). We're never going to push anything to cmip6-cmor-tables, so I think that renders other submodule/subtree distinctions moot.

I'm not wedded to the idea, however, and (fortunately!) this issue is orthogonal to everything else we're doing and can be considered/merged separately.

**Comment by tsjackson-noaa** [comment]
Changes to docs in the PR don't take into account the expanded docs from Jess's PR NOAA-GFDL/MDTF-diagnostics#98 -- will need to update when that gets merged.

**Comment by tsjackson-noaa** [comment]
Commit a9ea1f494e58bd8f76283b0820cbfdad167e66d5 merges in changes to the docs referred to in the previous comment.

**Comment by tsjackson-noaa** [comment]
Closing this issue since it has been implemented as of the [v3.0 beta 3](https://github.com/NOAA-GFDL/MDTF-diagnostics/releases/tag/v3.0-beta.3) release. See PR NOAA-GFDL/MDTF-diagnostics#147.
