### ISSUE TITLE
POD requires variables not available in the testable Input Data distributed with the software

### ISSUE THREAD

**Issue by jfbooth** [NOAA-GFDL/MDTF-diagnostics#91]
The POD my group is developing requires some variables that are not part of the testable Input Data. Should we request that you add more data? Right now, we have created our own testable data and arranged it in the same format as your test data. We could share it if needed.

**Comment by wrongkindofdoctor** [comment]
I'm not sure what the procedure is for adding test data so I'll consult @tsjackson-noaa to see if he knows.
@jkrasting is out for the rest of the month, so we might have to wait until January to finalize adding your files to the server.

**Comment by bitterbark** [comment]
As far as I know, I am  still responsible for making and posting the data
as tar files on an ftp server. Easiest for me would be to get the data from
you and post it on the ftp site, as long as it isn't too big. What is the
size estimate? Do you have an ftp or http site from which I could read it?

**Comment by bitterbark** [comment]
Sounds good.

**Comment by wrongkindofdoctor** [comment]
Thanks @bitterbark !
